import './globals.css'

import StyledComponentsRegistry from "@/lib/registry";
import { Montserrat } from "next/font/google";
import { Logo } from './components/Logo'


export const metadata = {
  title: 'Inbojobs - Autocomplete CV with AI',
  description: 'Generated by create next app'
}

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: "400",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
     <html lang='en'>      
        <body className={montserrat.className}>
          <StyledComponentsRegistry>
            <header className='py-10'>
              <h1 className='flex flex-col items-center justify-center text-4x'>
                <Logo />
                <strong> Autocomplete CV with AI </strong>
              </h1>
            </header>
            
            {children}
          </StyledComponentsRegistry>
        </body>
    </html>
      
    </>
  );
}