import './globals.css'
import { Inter } from 'next/font/google'
import { Logo } from './components/Logo'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Inbojobs - Autocomplete CV with AI',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <header className='py-10'>
          <h1 className='flex flex-col items-center justify-center text-4x'>
            <Logo />
            <strong>
              Autocomplete CV with AI
            </strong>
          </h1>
        </header>
        {children}
      </body>
    </html>
  )
}
