import './globals.css'

// import StyledComponentsRegistry from "@/lib/registry";
import { Montserrat } from "next/font/google";


import { AuthProvider } from './components/Auth-provider'

export const metadata = {
  title: 'Inbojobs - Autocomplete CV with AI',
  description: 'Generated by create next app'
}

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: "400",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
     <html lang='en'>      
        <body className={montserrat.className}>
            <AuthProvider>
              {children}
            </AuthProvider>
        </body>
    </html>
      
    </>
  );
}